-- ============================================================
-- UnikTap · вузы Шымкента: контакты и образовательные программы
--
-- Источники (проверено 24.08.2026):
--   univision.kz — карточки вузов, списки образовательных программ,
--                  профильные предметы ЕНТ, стоимость обучения
--   univery.kz   — телефоны приёмных комиссий, адреса
--
-- Чего нет в источниках, того нет и здесь: пустые поля оставлены пустыми,
-- цены без публикации — null, проходные баллы не заполнены совсем.
--
-- Что стоит проверить руками в админке:
--   • тип вуза (взят из классификации univision.kz),
--   • наличие военной кафедры и общежития — по умолчанию «нет»,
--   • стоимость обучения там, где вуз её не публикует,
--   • проходные баллы на грант.
--
-- Скрипт безопасно запускать повторно.
-- ============================================================

-- Стоимость может быть неизвестна: 0 значит «бесплатно», поэтому нужен null
alter table public.university_majors alter column fee_per_year drop not null;

-- ── Справочник групп образовательных программ ────────────────────────
insert into public.specialties (code, group_code, name_ru, direction_ru, subject_1_id, subject_2_id, is_active)
select v.code, '', v.name, v.direction, s1.id, s2.id, true
from (values
  ('B001', 'Педагогика и психология', 'Педагогические науки', 'biology', 'geography'),
  ('B002', 'Дошкольное обучение и воспитание', 'Педагогические науки', 'biology', 'geography'),
  ('B003', 'Педагогика и методика начального обучения', 'Педагогические науки', 'biology', 'geography'),
  ('B004', 'Подготовка учителей начальной военной подготовки', 'Педагогические науки', 'creative', 'creative'),
  ('B005', 'Подготовка учителей физической культуры', 'Педагогические науки', 'creative', 'creative'),
  ('B006', 'Подготовка учителей музыки', 'Педагогические науки', 'creative', 'creative'),
  ('B007', 'Подготовка учителей художественного труда и черчения', 'Педагогические науки', 'creative', 'creative'),
  ('B008', 'Подготовка учителей основ права и экономики', 'Педагогические науки', 'world_hist', 'geography'),
  ('B009', 'Подготовка учителей математики', 'Педагогические науки', 'math', 'physics'),
  ('B010', 'Подготовка учителей физики', 'Педагогические науки', 'math', 'physics'),
  ('B011', 'Подготовка учителей информатики', 'Педагогические науки', 'math', 'informatics'),
  ('B012', 'Подготовка учителей химии', 'Педагогические науки', 'biology', 'chemistry'),
  ('B013', 'Подготовка учителей биологии', 'Педагогические науки', 'biology', 'chemistry'),
  ('B014', 'Подготовка учителей географии', 'Педагогические науки', 'world_hist', 'geography'),
  ('B015', 'Подготовка учителей по гуманитарным предметам', 'Педагогические науки', 'world_hist', 'geography'),
  ('B016', 'Подготовка учителей казахского языка и литературы', 'Педагогические науки', 'kazakh', 'literature'),
  ('B017', 'Подготовка учителей русского языка и литературы', 'Педагогические науки', 'russian', 'literature'),
  ('B018', 'Подготовка учителей иностранного языка', 'Педагогические науки', 'english', 'world_hist'),
  ('B019', 'Подготовка социальных педагогов', 'Педагогические науки', 'biology', 'geography'),
  ('B020', 'Специальная педагогика', 'Педагогические науки', 'biology', 'geography'),
  ('B021', 'Исполнительское искусство', 'Искусство', 'creative', 'creative'),
  ('B027', 'Театральное искусство', 'Искусство', 'creative', 'creative'),
  ('B028', 'Хореография', 'Искусство', 'creative', 'creative'),
  ('B030', 'Изобразительное искусство', 'Искусство', 'creative', 'creative'),
  ('B031', 'Мода, дизайн', 'Искусство', 'creative', 'creative'),
  ('B032', 'Философия и этика', 'Искусство', 'world_hist', 'geography'),
  ('B033', 'Религия и теология', 'Искусство', 'creative', 'creative'),
  ('B034', 'История', 'Гуманитарные науки', 'world_hist', 'geography'),
  ('B036', 'Переводческое дело', 'Гуманитарные науки', 'english', 'world_hist'),
  ('B037', 'Филология', 'Гуманитарные науки', 'kazakh', 'literature'),
  ('B038', 'Социология', 'Социальные науки', 'math', 'geography'),
  ('B040', 'Политология', 'Социальные науки', 'english', 'world_hist'),
  ('B041', 'Психология', 'Социальные науки', 'biology', 'geography'),
  ('B042', 'Журналистика и репортерское дело', 'Социальные науки', 'creative', 'creative'),
  ('B043', 'Библиотечное дело, обработка информации и архивное дело', 'Социальные науки', 'kazakh', 'literature'),
  ('B044', 'Менеджмент и управление', 'Бизнес и управление', 'math', 'geography'),
  ('B045', 'Аудит и налогообложение', 'Бизнес и управление', 'math', 'geography'),
  ('B046', 'Финансы, экономика, банковское и страховое дело', 'Бизнес и управление', 'math', 'geography'),
  ('B047', 'Маркетинг и реклама', 'Бизнес и управление', 'math', 'geography'),
  ('B049', 'Право', 'Юридические науки', 'world_hist', 'law'),
  ('B050', 'Биологические и смежные науки', 'Естественные науки', 'biology', 'chemistry'),
  ('B051', 'Окружающая среда', 'Естественные науки', 'biology', 'geography'),
  ('B052', 'Наука о земле', 'Естественные науки', 'math', 'geography'),
  ('B053', 'Химия', 'Естественные науки', 'biology', 'chemistry'),
  ('B054', 'Физика', 'Естественные науки', 'math', 'physics'),
  ('B055', 'Математика и статистика', 'Естественные науки', 'math', 'physics'),
  ('B057', 'Информационные технологии', 'Информационно-коммуникационные технологии', 'math', 'informatics'),
  ('B059', 'Коммуникации и коммуникационные технологии', 'Информационно-коммуникационные технологии', 'math', 'physics'),
  ('B060', 'Химическая инженерия и процессы', 'Инженерные науки', 'chemistry', 'physics'),
  ('B061', 'Материаловедение и технологии', 'Инженерные науки', 'math', 'physics'),
  ('B062', 'Электротехника и электроэнергетика', 'Инженерные науки', 'math', 'physics'),
  ('B063', 'Электротехника и автоматизация', 'Инженерные науки', 'math', 'physics'),
  ('B064', 'Механика и металлообработка', 'Инженерные науки', 'math', 'physics'),
  ('B065', 'Транспортная техника и технологии', 'Инженерные науки', 'math', 'physics'),
  ('B068', 'Производство продуктов питания', 'Инженерные науки', 'biology', 'chemistry'),
  ('B069', 'Производство материалов (стекло, бумага, пластик, дерево)', 'Инженерные науки', 'math', 'physics'),
  ('B070', 'Текстиль: одежда, обувь и кожаные изделия', 'Инженерные науки', 'math', 'physics'),
  ('B071', 'Горное дело и добыча полезных ископаемых', 'Инженерные науки', 'math', 'physics'),
  ('B072', 'Технология фармацевтического производства', 'Инженерные науки', 'biology', 'chemistry'),
  ('B073', 'Архитектура', 'Инженерные науки', 'creative', 'creative'),
  ('B074', 'Градостроительство, строительные работы и гражданское строительство', 'Инженерные науки', 'math', 'physics'),
  ('B075', 'Кадастр и землеустройство', 'Инженерные науки', 'math', 'geography'),
  ('B076', 'Стандартизация, сертификация и метрология (по отраслям)', 'Инженерные науки', 'math', 'physics'),
  ('B077', 'Растениеводство', 'Сельское хозяйство', 'biology', 'chemistry'),
  ('B078', 'Животноводство', 'Сельское хозяйство', 'biology', 'chemistry'),
  ('B082', 'Водные ресурсы и водопользования', 'Сельское хозяйство', 'math', 'physics'),
  ('B084', 'Сестринское дело', 'Здравоохранение', 'biology', 'chemistry'),
  ('B085', 'Фармация', 'Здравоохранение', 'biology', 'chemistry'),
  ('B086', 'Общая медицина', 'Здравоохранение', 'biology', 'chemistry'),
  ('B087', 'Стоматология', 'Здравоохранение', 'biology', 'chemistry'),
  ('B088', 'Педиатрия', 'Здравоохранение', 'biology', 'chemistry'),
  ('B089', 'Общественное здоровье', 'Здравоохранение', 'biology', 'chemistry'),
  ('B090', 'Социальная работа', 'Услуги', 'biology', 'geography'),
  ('B091', 'Туризм', 'Услуги', 'geography', 'english'),
  ('B092', 'Досуг', 'Услуги', 'creative', 'creative'),
  ('B093', 'Ресторанное дело и гостиничный бизнес', 'Услуги', 'geography', 'english'),
  ('B094', 'Санитарно-профилактические мероприятия', 'Услуги', 'math', 'physics'),
  ('B095', 'Транспортные услуги', 'Услуги', 'math', 'geography'),
  ('B134', 'Археология и этнология', 'Гуманитарные науки', 'world_hist', 'geography'),
  ('B140', 'Международные отношения и дипломатия', 'Социальные науки', 'english', 'world_hist'),
  ('B183', 'Агроинженерия', 'Сельское хозяйство', 'math', 'physics'),
  ('B271', 'Нефтегазовое дело', 'Инженерные науки', null, null)
) as v(code, name, direction, c1, c2)
left join public.ent_subjects s1 on s1.code = v.c1
left join public.ent_subjects s2 on s2.code = v.c2
on conflict (code) do update set
  name_ru = excluded.name_ru,
  direction_ru = excluded.direction_ru,
  subject_1_id = excluded.subject_1_id,
  subject_2_id = excluded.subject_2_id,
  is_active = true;

-- ── Чистка выдуманных демо-данных у ЮКУ им. Ауэзова ──────────────────
delete from public.university_majors
where university_id = (select id from public.universities where slug = 'auezov-university');

delete from public.admission_blocks
where university_id = (select id from public.universities where slug = 'auezov-university')
  and kind = 'deadline';

update public.universities set
  dormitory_info_ru = '', dormitory_info_kk = '', license_number = '',
  accreditation_ru = '', accreditation_kk = '', whatsapp = '', working_hours_ru = '',
  has_military_department = false, has_dormitory = false
where slug = 'auezov-university';

-- ── Университеты ─────────────────────────────────────────────────────
insert into public.universities (
  slug, name_ru, name_kk, short_name, abbr, city_id, address_ru, phones, email, website,
  type, founded_year, students_count, teachers_count, description_ru, is_published, sort_order
) values
  ('auezov-university', 'Южно-Казахстанский университет имени М. Ауэзова', 'М. Әуезов атындағы Оңтүстік Қазақстан университеті', 'Auezov University', 'ЮКУ',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, пр. Тауке хана, 5',
   array['+7 (7252) 21-01-41', '+7 (7252) 21-08-94', '+7 (747) 275-75-00'], 'rector@auezov.edu.kz', 'https://auezov.edu.kz', 'state'::university_type,
   1943, 17007, 1622, 'Крупнейший многопрофильный университет юга Казахстана. Ведёт историю с 1943 года, сегодня — 166 программ бакалавриата, более 17 тысяч студентов.', true, 10),
  ('skma-shymkent', 'Южно-Казахстанская медицинская академия', 'Оңтүстік Қазақстан медицина академиясы', 'ЮКМА', 'ЮКМА',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, площадь Аль-Фараби, 1',
   array['+7 (7252) 39-57-57', '+7 (7252) 40-82-22', '+7 (7252) 40-82-08'], '', 'https://skma.edu.kz', 'international'::university_type,
   1979, 4324, 405, 'Медицинский вуз Шымкента, основан в 1979 году. Бакалавриат, интернатура, резидентура и докторантура по медицине, стоматологии, фармации и общественному здравоохранению.', true, 11),
  ('miras-university', 'Университет «Мирас»', '«Мирас» университеті', 'Мирас', 'Мирас',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. Гани Иляева, 3',
   array['+7 (7252) 33-77-77', '+7 775 007-30-00', '+7 702 777-55-33'], '', 'https://miras.edu.kz', 'private'::university_type,
   1997, 5471, 154, 'Частный университет Шымкента, основан в 1997 году. Экономика, право, информационные технологии, педагогика, дизайн и туризм. Обучение на трёх языках.', true, 12),
  ('zhanibekov-university', 'Южно-Казахстанский педагогический университет имени Өзбекәлі Жәнібекова', 'Өзбекәлі Жәнібеков атындағы Оңтүстік Қазақстан педагогикалық университеті', 'ЮКПУ', 'ЮКПУ',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. А. Байтурсынова, 13',
   array['+7 (7252) 30-14-59', '+7 (7252) 21-41-01', '+7 708 438-65-62'], '', 'https://okmpi.kz', 'national'::university_type,
   1937, 5773, 432, 'Один из старейших педагогических вузов страны, основан в 1937 году. 55 программ бакалавриата по педагогическим и гуманитарным направлениям.', true, 13),
  ('udn-kuatbekov', 'Университет дружбы народов имени академика А. Куатбекова', 'Академик Ә. Қуатбеков атындағы Халықтар достығы университеті', 'УДН', 'УДН',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. Толе би, 32',
   array['+7 (7252) 95-25-85', '+7 (7252) 95-25-21', '+7 (7252) 95-25-01'], '', 'https://udn.edu.kz', 'national'::university_type,
   2000, 10346, 472, 'Университет основан в 2000 году, назван в честь академика-химика Абдымусы Куатбекова. Обучение на казахском, русском и английском языках.', true, 14),
  ('tashenev-university', 'Университет имени Жумабека Ахметулы Ташенева', 'Жұмабек Ахметұлы Тәшенев атындағы университет', 'Университет Ташенева', 'УТ',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, пр. Кунаева, 21',
   array['+7 (7252) 53-71-52', '+7 702 161-93-84', '+7 776 104-70-70'], '', 'https://tashenev.edu.kz', 'national'::university_type,
   1998, 9377, 388, 'Вуз ведёт историю с 1998 года от университета «Сырдария». 60 программ бакалавриата, более девяти тысяч студентов.', true, 15),
  ('caiu-shymkent', 'Центрально-Азиатский инновационный университет', 'Орталық Азия инновациялық университеті', 'ЦАИУ', 'ЦАИУ',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. Мадели Кожа, 137/1',
   array['+7 (7252) 53-04-21', '+7 (7252) 53-56-95', '+7 707 510-10-10'], '', 'https://caiu.edu.kz', 'private'::university_type,
   2021, 12475, 482, 'Образован в 2021 году слиянием Международного гуманитарно-технического университета и Института имени М. Сапарбаева. 47 программ бакалавриата.', true, 16),
  ('shymkent-university', 'Шымкентский университет', 'Шымкент университеті', 'ШымУ', 'ШымУ',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. Жибек жолы, 6',
   array['+7 (7252) 55-58-61'], '', 'https://univershu.edu.kz', 'private'::university_type,
   null, null, null, 'Многопрофильный вуз Шымкента: педагогика, экономика, право, информационные технологии и естественные науки.', true, 17),
  ('rsiu-shymkent', 'Региональный социально-инновационный университет', 'Аймақтық әлеуметтік-инновациялық университеті', 'РСИУ', 'РСИУ',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. Терешковой, 14а',
   array['+7 (7252) 53-85-70', '+7 (7252) 53-89-22'], '', 'https://rsiu.kz', 'national'::university_type,
   null, null, null, 'Университет в Шымкенте. Список образовательных программ уточняется.', true, 18),
  ('hgti-shymkent', 'Международный гуманитарно-технический институт', 'Халықаралық гуманитарлық-техникалық институт', 'МГТИ', 'МГТИ',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. Байтурсынова, 80',
   array['+7 (7252) 37-12-87', '+7 (7252) 37-12-86', '+7 (7252) 77-15-52'], '', 'https://hgtu.kz', 'national'::university_type,
   null, null, null, 'Институт в Шымкенте. Список образовательных программ уточняется.', true, 19),
  ('silkway-university', 'Международный университет Silkway', 'Silkway халықаралық университеті', 'Silkway', 'SWIU',
   (select id from public.cities where slug = 'shymkent'), 'г. Шымкент, ул. Жангельдина, 13',
   array['+7 (7252) 31-03-32', '+7 (7252) 53-71-52'], '', 'https://swiu.kz', 'private'::university_type,
   null, null, null, 'Частный университет в Шымкенте. Список образовательных программ уточняется.', true, 20)
on conflict (slug) do update set
  name_ru = excluded.name_ru, name_kk = excluded.name_kk,
  short_name = excluded.short_name, abbr = excluded.abbr,
  city_id = excluded.city_id, address_ru = excluded.address_ru,
  phones = excluded.phones, email = excluded.email, website = excluded.website,
  type = excluded.type, founded_year = excluded.founded_year,
  students_count = excluded.students_count, teachers_count = excluded.teachers_count,
  description_ru = excluded.description_ru, is_published = true, deleted_at = null;

-- ── Образовательные программы вузов ──────────────────────────────────
insert into public.university_majors (
  university_id, specialty_id, degree, study_forms, languages, duration_years,
  fee_per_year, is_published, sort_order
)
select u.id, s.id, 'bachelor'::degree_level, '{full_time}'::study_form[], '{ru,kk}'::text[], 4,
       v.fee, true, 100
from (values
  ('auezov-university', 'B001', 757000),
  ('auezov-university', 'B002', 757000),
  ('auezov-university', 'B003', 757000),
  ('auezov-university', 'B004', 757000),
  ('auezov-university', 'B005', 757000),
  ('auezov-university', 'B006', 757000),
  ('auezov-university', 'B007', 757000),
  ('auezov-university', 'B009', 757000),
  ('auezov-university', 'B010', 757000),
  ('auezov-university', 'B011', 757000),
  ('auezov-university', 'B012', 757000),
  ('auezov-university', 'B013', 757000),
  ('auezov-university', 'B014', 757000),
  ('auezov-university', 'B015', 757000),
  ('auezov-university', 'B016', 757000),
  ('auezov-university', 'B017', 757000),
  ('auezov-university', 'B018', 757000),
  ('auezov-university', 'B020', 757000),
  ('auezov-university', 'B027', 757000),
  ('auezov-university', 'B028', 757000),
  ('auezov-university', 'B030', 757000),
  ('auezov-university', 'B031', 757000),
  ('auezov-university', 'B032', 757000),
  ('auezov-university', 'B033', 757000),
  ('auezov-university', 'B034', 757000),
  ('auezov-university', 'B036', 757000),
  ('auezov-university', 'B037', 757000),
  ('auezov-university', 'B040', 757000),
  ('auezov-university', 'B041', 757000),
  ('auezov-university', 'B042', 757000),
  ('auezov-university', 'B043', 757000),
  ('auezov-university', 'B044', 757000),
  ('auezov-university', 'B045', 757000),
  ('auezov-university', 'B046', 757000),
  ('auezov-university', 'B047', 757000),
  ('auezov-university', 'B049', 757000),
  ('auezov-university', 'B050', 757000),
  ('auezov-university', 'B051', 757000),
  ('auezov-university', 'B052', 757000),
  ('auezov-university', 'B053', 757000),
  ('auezov-university', 'B054', 757000),
  ('auezov-university', 'B055', 757000),
  ('auezov-university', 'B057', 757000),
  ('auezov-university', 'B059', 757000),
  ('auezov-university', 'B060', 757000),
  ('auezov-university', 'B061', 757000),
  ('auezov-university', 'B062', 757000),
  ('auezov-university', 'B063', 757000),
  ('auezov-university', 'B064', 757000),
  ('auezov-university', 'B065', 757000),
  ('auezov-university', 'B068', 757000),
  ('auezov-university', 'B069', 757000),
  ('auezov-university', 'B070', 757000),
  ('auezov-university', 'B071', 757000),
  ('auezov-university', 'B072', 757000),
  ('auezov-university', 'B074', 757000),
  ('auezov-university', 'B075', 757000),
  ('auezov-university', 'B076', 757000),
  ('auezov-university', 'B077', 757000),
  ('auezov-university', 'B078', 757000),
  ('auezov-university', 'B082', 757000),
  ('auezov-university', 'B090', 757000),
  ('auezov-university', 'B091', 757000),
  ('auezov-university', 'B092', 757000),
  ('auezov-university', 'B093', 757000),
  ('auezov-university', 'B094', 757000),
  ('auezov-university', 'B095', 757000),
  ('auezov-university', 'B134', 757000),
  ('auezov-university', 'B140', 757000),
  ('auezov-university', 'B183', 757000),
  ('auezov-university', 'B271', 757000),
  ('skma-shymkent', 'B072', 900000),
  ('skma-shymkent', 'B084', 900000),
  ('skma-shymkent', 'B085', 1000000),
  ('skma-shymkent', 'B086', 1300000),
  ('skma-shymkent', 'B087', 1800000),
  ('skma-shymkent', 'B088', 1200000),
  ('skma-shymkent', 'B089', 900000),
  ('miras-university', 'B001', 510000),
  ('miras-university', 'B002', 510000),
  ('miras-university', 'B003', 510000),
  ('miras-university', 'B005', 510000),
  ('miras-university', 'B007', 510000),
  ('miras-university', 'B009', 510000),
  ('miras-university', 'B011', 510000),
  ('miras-university', 'B012', 510000),
  ('miras-university', 'B016', 510000),
  ('miras-university', 'B017', 510000),
  ('miras-university', 'B018', 510000),
  ('miras-university', 'B020', 510000),
  ('miras-university', 'B031', 510000),
  ('miras-university', 'B042', 510000),
  ('miras-university', 'B044', 510000),
  ('miras-university', 'B045', 510000),
  ('miras-university', 'B046', 510000),
  ('miras-university', 'B049', 510000),
  ('miras-university', 'B057', 510000),
  ('miras-university', 'B059', 510000),
  ('miras-university', 'B091', 510000),
  ('zhanibekov-university', 'B001', null),
  ('zhanibekov-university', 'B002', null),
  ('zhanibekov-university', 'B003', null),
  ('zhanibekov-university', 'B004', null),
  ('zhanibekov-university', 'B005', null),
  ('zhanibekov-university', 'B006', null),
  ('zhanibekov-university', 'B007', null),
  ('zhanibekov-university', 'B008', null),
  ('zhanibekov-university', 'B009', null),
  ('zhanibekov-university', 'B010', null),
  ('zhanibekov-university', 'B011', null),
  ('zhanibekov-university', 'B012', null),
  ('zhanibekov-university', 'B013', null),
  ('zhanibekov-university', 'B014', null),
  ('zhanibekov-university', 'B015', null),
  ('zhanibekov-university', 'B016', null),
  ('zhanibekov-university', 'B017', null),
  ('zhanibekov-university', 'B018', null),
  ('zhanibekov-university', 'B019', null),
  ('zhanibekov-university', 'B020', null),
  ('zhanibekov-university', 'B031', null),
  ('zhanibekov-university', 'B036', null),
  ('zhanibekov-university', 'B037', null),
  ('zhanibekov-university', 'B050', null),
  ('udn-kuatbekov', 'B001', null),
  ('udn-kuatbekov', 'B002', null),
  ('udn-kuatbekov', 'B003', null),
  ('udn-kuatbekov', 'B005', null),
  ('udn-kuatbekov', 'B006', null),
  ('udn-kuatbekov', 'B009', null),
  ('udn-kuatbekov', 'B011', null),
  ('udn-kuatbekov', 'B012', null),
  ('udn-kuatbekov', 'B013', null),
  ('udn-kuatbekov', 'B014', null),
  ('udn-kuatbekov', 'B015', null),
  ('udn-kuatbekov', 'B016', null),
  ('udn-kuatbekov', 'B017', null),
  ('udn-kuatbekov', 'B018', null),
  ('udn-kuatbekov', 'B020', null),
  ('udn-kuatbekov', 'B031', null),
  ('udn-kuatbekov', 'B044', null),
  ('udn-kuatbekov', 'B045', null),
  ('udn-kuatbekov', 'B046', null),
  ('udn-kuatbekov', 'B047', null),
  ('udn-kuatbekov', 'B049', null),
  ('udn-kuatbekov', 'B057', null),
  ('udn-kuatbekov', 'B059', null),
  ('udn-kuatbekov', 'B060', null),
  ('udn-kuatbekov', 'B062', null),
  ('udn-kuatbekov', 'B073', null),
  ('udn-kuatbekov', 'B074', null),
  ('tashenev-university', 'B001', null),
  ('tashenev-university', 'B002', null),
  ('tashenev-university', 'B003', null),
  ('tashenev-university', 'B005', null),
  ('tashenev-university', 'B006', null),
  ('tashenev-university', 'B007', null),
  ('tashenev-university', 'B009', null),
  ('tashenev-university', 'B010', null),
  ('tashenev-university', 'B011', null),
  ('tashenev-university', 'B012', null),
  ('tashenev-university', 'B013', null),
  ('tashenev-university', 'B014', null),
  ('tashenev-university', 'B015', null),
  ('tashenev-university', 'B016', null),
  ('tashenev-university', 'B017', null),
  ('tashenev-university', 'B018', null),
  ('tashenev-university', 'B021', null),
  ('tashenev-university', 'B031', null),
  ('tashenev-university', 'B043', null),
  ('tashenev-university', 'B044', null),
  ('tashenev-university', 'B045', null),
  ('tashenev-university', 'B046', null),
  ('tashenev-university', 'B049', null),
  ('tashenev-university', 'B050', null),
  ('tashenev-university', 'B057', null),
  ('caiu-shymkent', 'B001', null),
  ('caiu-shymkent', 'B002', null),
  ('caiu-shymkent', 'B003', null),
  ('caiu-shymkent', 'B004', null),
  ('caiu-shymkent', 'B005', null),
  ('caiu-shymkent', 'B006', null),
  ('caiu-shymkent', 'B007', null),
  ('caiu-shymkent', 'B009', null),
  ('caiu-shymkent', 'B010', null),
  ('caiu-shymkent', 'B011', null),
  ('caiu-shymkent', 'B012', null),
  ('caiu-shymkent', 'B013', null),
  ('caiu-shymkent', 'B014', null),
  ('caiu-shymkent', 'B015', null),
  ('caiu-shymkent', 'B016', null),
  ('caiu-shymkent', 'B017', null),
  ('caiu-shymkent', 'B018', null),
  ('caiu-shymkent', 'B031', null),
  ('caiu-shymkent', 'B036', null),
  ('caiu-shymkent', 'B044', null),
  ('caiu-shymkent', 'B045', null),
  ('caiu-shymkent', 'B046', null),
  ('caiu-shymkent', 'B049', null),
  ('caiu-shymkent', 'B051', null),
  ('caiu-shymkent', 'B057', null),
  ('caiu-shymkent', 'B091', null),
  ('shymkent-university', 'B001', null),
  ('shymkent-university', 'B003', null),
  ('shymkent-university', 'B005', null),
  ('shymkent-university', 'B006', null),
  ('shymkent-university', 'B007', null),
  ('shymkent-university', 'B009', null),
  ('shymkent-university', 'B010', null),
  ('shymkent-university', 'B011', null),
  ('shymkent-university', 'B012', null),
  ('shymkent-university', 'B013', null),
  ('shymkent-university', 'B014', null),
  ('shymkent-university', 'B015', null),
  ('shymkent-university', 'B016', null),
  ('shymkent-university', 'B017', null),
  ('shymkent-university', 'B018', null),
  ('shymkent-university', 'B038', null),
  ('shymkent-university', 'B044', null),
  ('shymkent-university', 'B045', null),
  ('shymkent-university', 'B046', null),
  ('shymkent-university', 'B049', null),
  ('shymkent-university', 'B050', null),
  ('shymkent-university', 'B057', null)
) as v(uslug, scode, fee)
join public.universities u on u.slug = v.uslug
join public.specialties s on s.code = v.scode
on conflict (university_id, specialty_id, degree) do update set
  fee_per_year = excluded.fee_per_year,
  is_published = true,
  deleted_at = null;

-- ── Пересчёт агрегатов ───────────────────────────────────────────────
update public.universities u set
  majors_count  = (select count(*) from public.university_majors m
                     where m.university_id = u.id and m.is_published and m.deleted_at is null),
  min_ent_score = (select min(m.grant_score) from public.university_majors m
                     where m.university_id = u.id and m.is_published and m.deleted_at is null),
  min_fee       = (select min(nullif(m.fee_per_year, 0)) from public.university_majors m
                     where m.university_id = u.id and m.is_published and m.deleted_at is null);

-- ── Проверка ─────────────────────────────────────────────────────────
select u.name_ru as вуз, u.majors_count as программ,
       coalesce(u.min_fee::text, 'не опубликована') as цена_от
from public.universities u
join public.cities c on c.id = u.city_id
where c.slug = 'shymkent' and u.deleted_at is null
order by u.sort_order;

-- ── Демо-вузы Алматы и Астаны (данные придуманы для примера) ──────────
-- Раскомментируйте, если хотите убрать их из каталога:
-- update public.universities set is_published = false
-- where slug in ('satbayev-university', 'nazarbayev-university');

